/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screen;

import Screen.Cadastrar.CadastrarArmazem;
import Screen.Cadastrar.CadastrarMovimentacoes;
import Screen.Cadastrar.CadastrarProduto;
import Screen.gerenciar.GerenciarEstoque;
import javax.swing.JOptionPane;

/**
 *
 * @author ve743
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuCadastrarProducao = new javax.swing.JMenuItem();
        MenuCadastrarArmazem = new javax.swing.JMenuItem();
        MenuCadastrarMovimentacoes = new javax.swing.JMenuItem();
        MenuGerenciarEstoque = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuAjudaSuporte = new javax.swing.JMenu();
        AjudaSuporte = new javax.swing.JMenuItem();
        MenuAjudaSair = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setText("estooker - app");

        jMenu1.setText("cadastrar");

        MenuCadastrarProducao.setText("produto");
        MenuCadastrarProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarProducaoActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCadastrarProducao);

        MenuCadastrarArmazem.setText("armazem");
        MenuCadastrarArmazem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarArmazemActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCadastrarArmazem);

        MenuCadastrarMovimentacoes.setText("movimentações");
        MenuCadastrarMovimentacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadastrarMovimentacoesActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCadastrarMovimentacoes);

        jMenuBar1.add(jMenu1);

        MenuGerenciarEstoque.setText("gerenciar");

        jMenuItem4.setText("gerenciar estoque");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuGerenciarEstoque.add(jMenuItem4);

        jMenuBar1.add(MenuGerenciarEstoque);

        MenuAjudaSuporte.setText("ajuda");

        AjudaSuporte.setText("suporte");
        AjudaSuporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjudaSuporteActionPerformed(evt);
            }
        });
        MenuAjudaSuporte.add(AjudaSuporte);

        MenuAjudaSair.setText("sair");
        MenuAjudaSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAjudaSairActionPerformed(evt);
            }
        });
        MenuAjudaSuporte.add(MenuAjudaSair);

        jMenuBar1.add(MenuAjudaSuporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(1038, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(688, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // menus cadastrar
    private void MenuCadastrarArmazemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarArmazemActionPerformed
        CadastrarArmazem tela = new CadastrarArmazem(this, false);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        
    }//GEN-LAST:event_MenuCadastrarArmazemActionPerformed
    
    //menu ajuda
    private void AjudaSuporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjudaSuporteActionPerformed
        JOptionPane.showMessageDialog(null, "Acesse o site  https://www.indemil.com.br");
    }//GEN-LAST:event_AjudaSuporteActionPerformed

    private void MenuAjudaSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAjudaSairActionPerformed
     System.exit(0);
    }//GEN-LAST:event_MenuAjudaSairActionPerformed

    private void MenuCadastrarProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarProducaoActionPerformed
        CadastrarProduto tela = new CadastrarProduto(this, false);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        
    }//GEN-LAST:event_MenuCadastrarProducaoActionPerformed

    private void MenuCadastrarMovimentacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarMovimentacoesActionPerformed
        CadastrarMovimentacoes tela = new CadastrarMovimentacoes(this, false);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        
    }//GEN-LAST:event_MenuCadastrarMovimentacoesActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        GerenciarEstoque tela = new GerenciarEstoque(this, false);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
//        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AjudaSuporte;
    private javax.swing.JMenuItem MenuAjudaSair;
    private javax.swing.JMenu MenuAjudaSuporte;
    private javax.swing.JMenuItem MenuCadastrarArmazem;
    private javax.swing.JMenuItem MenuCadastrarMovimentacoes;
    private javax.swing.JMenuItem MenuCadastrarProducao;
    private javax.swing.JMenu MenuGerenciarEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
